sfBulkUpload/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('upload.urls', namespace='upload')),
]

upload/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^save$', views.upload_file, name = "upload_file"),
    url(r'^static/download', views.send_file, name = "send_file"),
]

upload/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

upload/forms.py
from django import forms

class UploadFileForm(forms.Form):
    email_id = forms.EmailField(widget=forms.TextInput())
    file = forms.FileField()
    fallout_report=forms.BooleanField(required=False)

upload/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import *
import time
import os
from django.conf import settings
from upload.bulkUploader import *
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.staticfiles.templatetags.staticfiles import static
import tempfile, zipfile
from wsgiref.util import FileWrapper
import mimetypes
import cloudstorage as gcs
import re
error_message=0
def index(request):
	upload_form = UploadFileForm()
	global error_message
	temp_error_message=error_message
	error_message=0
	return render(request,"upload/index.html", {"upload_form":upload_form, 'error_message':str(temp_error_message)})

def upload_file(request):
	global error_message
	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
		if request.POST["email_id"]=="" or 'file' not in request.FILES:
			 error_message = 4
			 return HttpResponseRedirect(reverse('upload:index'))
		email_id = request.POST["email_id"]
		if not re.match(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$", email_id):
			error_message = 5
			return HttpResponseRedirect(reverse('upload:index'))
		if form.is_valid():
			email_id = request.POST["email_id"]
			filepath = handle_uploaded_file(request.FILES['file'])
			if filepath != False:
				error_message = Check(filepath,email_id) + 1
				return HttpResponseRedirect(reverse('upload:index'))
			else:
				return HttpResponseRedirect(reverse('upload:index'))
		else:
			print form.error
	return HttpResponse("Not success")

def handle_uploaded_file(f):
	fileName, fileExtension = os.path.splitext(f.name)
	if fileExtension != ".xlsx":
		global error_message
		error_message = 3
		return False
	filepath='/sfbulkupload.appspot.com/file_'+str(time.time()*1000)+fileExtension;
	with gcs.open(filepath, 'w') as destination:
		for chunk in f.chunks():
			destination.write(chunk)
		return filepath
	return False
	
def send_file(request):
	filename     =  settings.UPLOAD_TEMPLATE
	download_name = settings.UPLOAD_TEMPLATE
	wrapper      = FileWrapper(open(filename))
	content_type = mimetypes.guess_type(filename)[0]
	response     = HttpResponse(wrapper,content_type=content_type)
	response['Content-Length']      = os.path.getsize(filename)    
	response['Content-Disposition'] = "attachment; filename=%s"%download_name
	return response

upload/templates/upload/index.html
{% load staticfiles %}
<!--<link rel="stylesheet" type="text/css" href="{% static 'bootstrap3/css/bootstrap.css' %}" />-->

  <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">
        <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>

    <script src="{% static 'materialize/js/materialize.js' %}"></script>

 <nav class="blue accent-2">
    <div class="nav-wrapper row" style="padding-top: 1%;">

    	<div class="col s3">
    		
    		
      		    <img width="149" class="responsive-img" src="{% static 'image/flipkart_logo.png' %}">

  </div>
  
    </div>
  </nav>
<div class="row">
	<div class="col s2"></div>
	<div class='col s10'>
	<blockquote>
      <h4>SF Bulk Uploader: </h4>
      <h5>
	    {% if error_message == '1' %}
              <small class='red darken-3'>
                Your File was not valid! Error Report has been sent to your mail
                </small>
            {% endif %}
            {% if error_message == '2' %}
              <small class='light-green accent-3'>
                File was successfully uploaded to SF.
                </small>
            {% endif %}          
	{% if error_message == '3' %}
              <small class='red darken-3'>
                Please enter xlsx file only.
                </small>
            {% endif %}

	{% if error_message == '4' %}
              <small class='red darken-3'>
                Please enter both Excel file and Email ID both are required field.
                </small>
            {% endif %}
	{% if error_message == '5' %}
              <small class='red darken-3'>
                Enter valid Email ID.
                </small>
            {% endif %}

      </h5>
    </blockquote>
          
</div>
</div>
<div class="row">
  <div class="col s3"></div>
  <div class="col s6 push-s3">
		
<form method="post" action="{% url 'upload:upload_file' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="file-field input-field">
      <div class="btn">
        <span>File</span>
        {{upload_form.file}}
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <div class="row">
        <div class="input-field col s12">
          {{upload_form.email_id}}
          {{upload_form.email_id.label_tag}}
          
        </div>
      </div>
    
            <div class="row">
            	 <div class="col s3 push-s9">
            <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </div>
        </div>
        </form>
  </div>
  <div class="col s3"></div>
</div>
<div>
  <div class="row">
    <div class="col s5 push-s3">
<a class="btn waves-effect waves-light" href="{% url 'upload:send_file' %}">Download Upload Format</a>
</div>
</div>
</div>

  <script>
  $(document).ready(function() {
    $('select').material_select();
  });
  </script>